{"name": "登录异常，测试数据是：{'accounts': '', 'pwd': '123123', 'exp': '登录账号有误'}", "status": "passed", "parameters": [{"name": "args", "value": "{'accounts': '', 'pwd': '123123', 'exp': '登录账号有误'}"}], "start": 1629531950928, "stop": 1629531951048, "uuid": "5b764121-00ea-4b97-991e-c62ab97f0385", "historyId": "0d099d0c42d347ccbb497231f142247d", "testCaseId": "ec1071642d55a2fafea25ec18572e772", "fullName": "script.test_mtx_login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_mtx_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "WIN-0A2AUJ2TO0H"}, {"name": "thread", "value": "14596-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_mtx_login"}]}